language: node_js
node_js:
  - 15
  
script:
  - cd frontend
  - npm install
  - npm run test --passWithNoTests
  - npm run build
  - cd ../backend
  - npm install
  - npm run test --passWithNoTests

services:
  - postgresql
